# Basic
hostname    : ~
config      : ~
arch        : "depth_anything_v2"
model       : "depth_anything_v2_vits"
data        : "da_2k"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "depth_anything_v2_vits_da_2k"
save_dir    : ~
weights     : "zoo/vision/depth/depth_anything_v2/depth_anything_v2_vits/da_2k/depth_anything_v2_vits_da_2k.pth"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 200
steps       : ~
imgsz       : 518
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
encoder     : "vits"
features    : 64
out_channels: [48, 96, 192, 384]
pred_only   : True
format      : 2  # 0: grayscale, 1: color, 2: both
