# Basic
hostname    : ~
config      : ~
arch        : "depth_anything_v2"
model       : "depth_anything_v2_vitl"
data        : ~
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : ~
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 200
steps       : ~
imgsz       : 518
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
exist_ok    : False
verbose     : True

# Model Specific
encoder     : "vitl"
features    : 256
out_channels: [256, 512, 1024, 1024]
pred_only   : True
grayscale   : False
